### ISSUE TITLE
Instant crash when i click the import games icon

### ISSUE THREAD

**Issue by jazir5** [steamgriddb/steamgriddb-manager#35]
Program crashes, window goes completely white. Clicking inside the window does nothing, program is closable via right click on the taskbar icon

**Comment by doZennn** [comment]
Can you upload your log?
The log file is stored here: `%appdata%/steamgriddb-manager`

**Comment by jazir5** [comment]
[log.log](https://github.com/steamgriddb/steamgriddb-manager/files/3582135/log.log)

**Comment by doZennn** [comment]
I released 0.2.4 with some fixes. Can you try again?

**Comment by Matiiyahu** [comment]
Still happening for me on 0.2.6.
this.games.map is not a function also
[log.log](https://github.com/steamgriddb/steamgriddb-manager/files/3587623/log.log)

**Comment by doZennn** [comment]
Can you try again in using v0.3.0?

**Comment by Matiiyahu** [comment]
Different error, but still the same issue.
[log.log](https://github.com/steamgriddb/steamgriddb-manager/files/3591574/log.log)

**Comment by doZennn** [comment]
Oops, looks like I broke something on 0.3.0. Fixed it in 0.3.1.  
The Battle.net and Uplay errors are separate from this. Please open another issue for those.

**Comment by Matiiyahu** [comment]
![image](https://user-images.githubusercontent.com/55053109/64560290-855bc200-d348-11e9-950f-918e1186f294.png)
It's working

**Comment by cjhutchi** [comment]
Also experiencing a crash when attempting to load the `Import` screen.
```
[2019-09-09 18:18:57.445] [error] UnhandledRejection TypeError: this.games.map is not a function
    at t.value (file:///C:/Users/<redacted>/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:74938)
    at ma (file:///C:/Users/<redacted>/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:65520)
    at ya (file:///C:/Users/<redacted>/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:65315)
    at ql (file:///C:/Users/<redacted>/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:99598)
    at zl (file:///C:/Users/<redacted>/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:84005)
    at Fl (file:///C:/Users/<redacted>/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:81032)
    at Al (file:///C:/Users/<redacted>/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:79605)
    at file:///C:/Users/<redacted>/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:41756
    at t.unstable_runWithPriority (file:///C:/Users/<redacted>/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:51:3878)
    at uo (file:///C:/Users/<redacted>/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:41485)
```

**Comment by doZennn** [comment]
Please try again in v0.3.1.

**Comment by cjhutchi** [comment]
> Please try again with v0.3.2.

That seems to have resolved my issue.
